# Temporary Flutter config - delete when creating real Flutter project
name: kiro_setup_temp
description: Temporary setup for Kiro IDE

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true